- name: Git pull setup
  hosts: myhosts
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Print message
      ansible.builtin.debug:
        msg: Hello world

    - name: Add deploy user
      ansible.builtin.user:
        name: deploy

    - name: Create .ssh folder
      ansible.builtin.file:
        path: /home/deploy/.ssh/
        state: directory
        owner: deploy

    - name: Copy SSH key for GitHub
      ansible.builtin.copy:
        src: ~/.ssh/id_ed25519
        dest: /home/deploy/.ssh/id_ed25519
        mode: 0600
        owner: deploy

    - name: Add Github to known hosts
      ansible.builtin.known_hosts:
        name: github.com
        #key: github.com ssh-ed25519 SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU
        key: github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
      become: true
      become_user: deploy

    - name: Create repo folder
      ansible.builtin.file:
        path: /home/deploy/willemvandervegt/
        state: directory
        owner: deploy

    - name: Install git
      ansible.builtin.apt:
        name: git

    - name: Clone git repo
      ansible.builtin.git:
        dest: ~/willemvandervegt
        repo: git@github.com:HarmVanDerVegt/willemvandervegt.git
        version: master
      become: true
      become_user: deploy
